// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using O2Connect.Api.Persistence;

#nullable disable

namespace O2Connect.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("O2Connect.Api.Models.Store.AuthorizationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodeChallengeMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("Nonce")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("authorization_codes", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.AuthorizationSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("ClientDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("MissingScopes")
                        .HasColumnType("text[]");

                    b.Property<string>("RequestUriCode")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("RequestedScopes")
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("SessionId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("authorization_sessions", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AllowPar")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPlainPkce")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("AllowedAuthenticationMethods")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("AllowedGrantTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("AllowedResponseTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("JsonWebKeysUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId1")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<string[]>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("RequiresConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPkce")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresSecret")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId1");

                    b.HasIndex("Status");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.DeviceAuthorization", b =>
                {
                    b.Property<string>("DeviceCodeHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("AuthorizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeniedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastPollAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("UserCodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("character varying(100)");

                    b.HasKey("DeviceCodeHash");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserCodeHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("device_authorizations", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.ParEntry", b =>
                {
                    b.Property<string>("RequestUriCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodeChallengeMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("State")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RequestUriCode");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("par_entries", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Token");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByToken");

                    b.HasIndex("SessionId");

                    b.HasIndex("Subject");

                    b.HasIndex("Subject", "ClientId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.UserConsent", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientId")
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.AuthorizationCode", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.User", "User")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.AuthorizationSession", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("AuthorizationSessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.User", "User")
                        .WithMany("AuthorizationSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("O2Connect.Api.Models.AuthorizationRequestData", "Request", b1 =>
                        {
                            b1.Property<string>("AuthorizationSessionSessionId");

                            b1.Property<string>("ClientId")
                                .IsRequired();

                            b1.Property<string>("CodeChallenge");

                            b1.Property<string>("CodeChallengeMethod");

                            b1.Property<string>("Nonce");

                            b1.Property<string>("RedirectUri")
                                .IsRequired();

                            b1.Property<string>("ResponseMode");

                            b1.Property<string>("ResponseType")
                                .IsRequired();

                            b1.Property<string>("Scope");

                            b1.Property<string>("State");

                            b1.HasKey("AuthorizationSessionSessionId");

                            b1.ToTable("authorization_sessions");

                            b1
                                .ToJson("Request")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AuthorizationSessionSessionId");
                        });

                    b.Navigation("Client");

                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.Client", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.User", null)
                        .WithMany("Clients")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.DeviceAuthorization", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("DeviceAuthorizations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.User", "User")
                        .WithMany("DeviceAuthorizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.ParEntry", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("ParEntries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.RefreshToken", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.RefreshToken", "ReplacedBy")
                        .WithMany()
                        .HasForeignKey("ReplacedByToken")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("O2Connect.Api.Models.Store.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Subject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReplacedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.UserConsent", b =>
                {
                    b.HasOne("O2Connect.Api.Models.Store.Client", "Client")
                        .WithMany("Consents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2Connect.Api.Models.Store.User", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.Client", b =>
                {
                    b.Navigation("AuthorizationCodes");

                    b.Navigation("AuthorizationSessions");

                    b.Navigation("Consents");

                    b.Navigation("DeviceAuthorizations");

                    b.Navigation("ParEntries");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("O2Connect.Api.Models.Store.User", b =>
                {
                    b.Navigation("AuthorizationCodes");

                    b.Navigation("AuthorizationSessions");

                    b.Navigation("Clients");

                    b.Navigation("Consents");

                    b.Navigation("DeviceAuthorizations");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
